language: java
jdk: openjdk11


jobs:
  include:
    - stage: test-app-coordinator
      before_script: cd src/app-coordinator && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn verify
